# Use an official Python runtime as a parent image
FROM python:3.8-slim

# Set the working directory to /app
WORKDIR /app

# Copy the current directory contents into the container at /app
COPY . /app

# Install any needed packages specified in requirements.txt
RUN pip install --no-cache-dir -r requirements.txt

# Install watchdog for auto-reloading
RUN pip install watchdog

# Make port 5000 available to the world outside this container
EXPOSE 5000

# Use watchdog to run the Flask application
CMD ["watchmedo", "auto-restart", "--directory", ".", "--pattern=*.py", "--recursive", "--", "python", "app/main.py"]
