name: Build, Run, and Test Docker Image

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Build Docker image
      run: docker build -t imaginai-backend:latest .

    - name: Run Docker container and run tests
      run: docker run imaginai-backend:latest python -m unittest tests/test_app.py

    - name: Cleanup (optional)
      run: docker rmi imaginai-backend:latest